# Generated by Django 5.1.6 on 2025-02-12 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='skill',
        ),
        migrations.AddField(
            model_name='team',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='team.skill'),
            preserve_default=False,
        ),
    ]
