# Generated by Django 5.1.6 on 2025-02-12 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_team_skill_team_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.skill'),
        ),
    ]
